vfs_glusterfs: Samba VFS module for glusterfs
Implement a Samba VFS plugin for glusterfs based on gluster's gfapi.
This is a "bottom" vfs plugin (not something to be stacked on top of
another module), and translates (most) calls into closest actions
on gfapi.

Signed-off-by: Anand Avati <avati@redhat.com>

diff --git a/source3/configure.in b/source3/configure.in
--- a/source3/configure.in
+++ b/source3/configure.in
@@ -1186,6 +1186,28 @@ fi
 AC_SUBST(ONEFS_LIBS)
 LIBS="$save_LIBS"
 
+
+#############
+AC_ARG_ENABLE([glusterfs],
+       AC_HELP_STRING([--disable-glusterfs],[Do not build vfs_glusterfs module]))
+
+if test "x$enable_glusterfs" != "xno"; then
+   PKG_CHECK_MODULES([GLFS], [glusterfs-api >= 4], glfs_found=yes, glfs_found=no)
+fi
+
+if test "x$enable_glusterfs" = "xyes" -a "x$glfs_found" != "xyes"; then
+   echo "GFAPI not found in build system"
+   exit 1
+fi
+
+if test "x$glfs_found" = "xyes"; then
+    CFLAGS="$CFLAGS $GLFS_CFLAGS"
+    LDFLAGS="$LDFLAGS $GLFS_LDFLAGS"
+    LIBS="$LIBS $GLFS_LIBS"
+    default_shared_modules="$default_shared_modules vfs_glusterfs"
+fi
+
+
 # Note that all the libunwind symbols in the API are defined to internal
 # platform-specific version, so we must include libunwind.h before checking
 # any of them.
@@ -6979,6 +7001,7 @@ SMB_MODULE(vfs_scannedonly, \$(VFS_SCANNEDONLY_OBJ), "bin/scannedonly.$SHLIBEXT"
 SMB_MODULE(vfs_crossrename, \$(VFS_CROSSRENAME_OBJ), "bin/crossrename.$SHLIBEXT", VFS)
 SMB_MODULE(vfs_linux_xfs_sgid, \$(VFS_LINUX_XFS_SGID_OBJ), "bin/linux_xfs_sgid.$SHLIBEXT", VFS)
 SMB_MODULE(vfs_time_audit, \$(VFS_TIME_AUDIT_OBJ), "bin/time_audit.$SHLIBEXT", VFS)
+SMB_MODULE(vfs_glusterfs, \$(VFS_GLUSTERFS_OBJ), "bin/glusterfs.$SHLIBEXT", VFS)
 
 SMB_SUBSYSTEM(VFS,smbd/vfs.o)
 
